FROM python:3.13-slim

WORKDIR /app

COPY requirements_frontend.txt .

RUN pip install --no-cache-dir -r requirements_frontend.txt

COPY . .

CMD ["streamlit","run", "frontend/ui.py","--server.port=8501","--server.address=0.0.0.0"]
